// © 2023 27 Software
//
// ************************************************************************
// Author           : DXterity8 Version 8.6
// Created          : March 14, 2023 6:19:34 AM
// File             : RestEventHistoriesController.cs
// ************************************************************************

using System;
using System.Linq;
using System.Net;

using KnightsTour.CoreLibrary;
using KnightsTour.WebAPI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;

namespace WebAPI.RestControllers
{
    /// <summary>
    /// The extended REST event history endpoints.
    /// Generated On: March 14, 2023 at 6:19:34 AM by DXterity Solutions.
    /// Generated By: DXterity8 Version 8.6.0 (see https://dxteritysolutions.com/).
    /// </summary>
    /// <seealso cref="WebAPI.RestControllers" />
    /// <remarks>
    /// As this class is just one of 3 available API techniques, it is prefixed with "Rest" as namespace differentations are not respected in the APIController protocol.
    /// This class is never overwritten once initialized - feel free to extend it as required with your custom endpoints.
    /// </remarks>
    [EnableCors("*")]
    [Route("rest/eventhistories")]
    public class RestEventHistoriesController : RestEventHistoriesControllerBase
    {
        #region Extended Constructor(s)

        #endregion Extended Constructor(s)

        #region Extended Declarations
        #endregion Extended Declarations

        #region Extended Properties
        #endregion Extended Properties

        #region Extended Methods
        #endregion Extended Methods

    } // Class
} // Namespace