// © 2023 27 Software
//
// ************************************************************************
// Author           : DXterity8 Version 8.6
// Created          : October 14, 2023 11:18:11 AM
// File             : PuzzleBase.cs
// ************************************************************************

using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Text;
using System.Xml;
using System.Xml.Serialization;

using KnightsTour.CoreLibrary;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace KnightsTour
{
    /// <summary>
    /// The PuzzleBase class which tightly binds the model to the object.  Inherits <seealso cref="PuzzleLiteBase" /> and implements <seealso cref="KnightsTour.CoreLibrary.IEntity{T}" />
    /// Generated On: October 14, 2023 at 11:18:11 AM by DXterity Solutions.
    /// Generated By: DXterity8 Version 8.6.0 (see https://dxteritysolutions.com/).
    /// </summary>
    /// <remarks>
    /// This class will be regenerated when requested to stay in sync with your model.
    /// This class should NOT be modified - any extensions or overrides should be completed in the extended class <seealso cref="Puzzle" />.
    /// </remarks>
    public abstract class PuzzleBase : PuzzleLiteBase, KnightsTour.CoreLibrary.IEntity<int?>
    {
        #region Constructor(s)

        /// <summary>
        /// Initializes a new instance of the <see cref="PuzzleBase"/> class.
        /// Initializes a new instance of the <see cref="PuzzleBase"/> class initialized with default properties.
        /// </summary>
        public PuzzleBase() : base()
        {
            Initialize();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="PuzzleBase"/> class.
        /// Initializes a new empty instance of the PuzzleBase class with the given primary key.
        /// </summary>
        /// <param name="id">The primary key value.</param>
        public PuzzleBase(int? id)
        {
            Initialize();
            SetPrimaryKey(id);
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="PuzzleBase"/> class.
        /// Initializes a new empty instance of the PuzzleBase class from the record in a data reader populating only the Puzzle columns specified.
        /// </summary>
        /// <param name="record">A record returned from a database reader.</param>
        /// <param name="columnsToInclude">A list of <see cref="Enumerations.PuzzleProperty"/> if you want a sub set of properties populated.  Defaulted to null which will be translated to mean no filter and return all properties.</param>
        public PuzzleBase(IDataRecord record, List<Enumerations.PuzzleProperty> columnsToInclude = null)
        {
            Initialize();

            // If not specified, default to all columns.
            if (columnsToInclude == null)
            {
                columnsToInclude = new List<Enumerations.PuzzleProperty>() { Enumerations.PuzzleProperty.All };
            }

            // Primary key must always be passed.
            PuzzleId = record.ValueAs<int?>("PuzzleId");
            if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.PuzzleCode))
            {
                PuzzleCode = record.ValueAs<Guid>("PuzzleCode");
            }
            if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.BoardId))
            {
                BoardId = record.ValueAs<int?>("BoardId");
            }
            if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.DifficultyLevelId))
            {
                DifficultyLevelId = record.ValueAs<int?>("DifficultyLevelId");
            }
            if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.Path))
            {
                Path = record.ValueAs<string>("Path");
            }
            if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.PuzzleOfTheDayDate))
            {
                PuzzleOfTheDayDate = record.ValueAs<DateTime?>("PuzzleOfTheDayDate");
            }

            // Link the primary key to the base Id field.
            SetPrimaryKey(PuzzleId.Value);
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="PuzzleBase"/> class.
        /// Initializes a new empty instance of the PuzzleBase class from a DataRow with the Puzzle columns specified.
        /// </summary>
        /// <param name="record">A <see cref="DataRow"/>.</param>
        /// <param name="columnsToInclude">A list of <see cref="Enumerations.PuzzleProperty"/> if you want a sub set of properties populated.  Defaulted to null which will be translated to mean no filter and return all properties.</param>
        public PuzzleBase(DataRow record, List<Enumerations.PuzzleProperty> columnsToInclude = null)
        {
            if (record != null)
            {
                Initialize();

                // If not specified, default to all columns.
                if (columnsToInclude == null)
                {
                    columnsToInclude = new List<Enumerations.PuzzleProperty>() { Enumerations.PuzzleProperty.All };
                }

                // Primary key must always be passed.
                PuzzleId = record.ValueAs<int?>("PuzzleId");
                if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.PuzzleCode))
                {
                    PuzzleCode = record.ValueAs<Guid>("PuzzleCode");
                }
                if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.BoardId))
                {
                    BoardId = record.ValueAs<int?>("BoardId");
                }
                if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.DifficultyLevelId))
                {
                    DifficultyLevelId = record.ValueAs<int?>("DifficultyLevelId");
                }
                if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.Path))
                {
                    Path = record.ValueAs<string>("Path");
                }
                if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.PuzzleOfTheDayDate))
                {
                    PuzzleOfTheDayDate = record.ValueAs<DateTime?>("PuzzleOfTheDayDate");
                }

                // Link the primary key to the base Id field.
                SetPrimaryKey(PuzzleId.Value);
            }
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="PuzzleBase"/> class.
        /// Initializes a new empty instance of the PuzzleBase class from a DataRow with the Puzzle columns specified.
        /// </summary>
        /// <param name="puzzleLite">A <see cref="PuzzleLite"/>.</param>
        public PuzzleBase(PuzzleLite puzzleLite)
        {
            if (puzzleLite != null)
            {
                Initialize();

                // Base properties.
                PuzzleId = puzzleLite.PuzzleId.HasValue && puzzleLite.PuzzleId.Value <= 0 ? null : puzzleLite.PuzzleId;
                PuzzleCode = puzzleLite.PuzzleCode;
                BoardId = puzzleLite.BoardId.HasValue && puzzleLite.BoardId.Value <= 0 ? null : puzzleLite.BoardId;
                DifficultyLevelId = puzzleLite.DifficultyLevelId.HasValue && puzzleLite.DifficultyLevelId.Value <= 0 ? null : puzzleLite.DifficultyLevelId;
                Path = puzzleLite.Path;
                PuzzleOfTheDayDate = puzzleLite.PuzzleOfTheDayDate;

                // Also convert the lite FK reference objects.
                if (puzzleLite.Board != null)
                {
                    this.Board = new Board(puzzleLite.Board);
                }
                if (puzzleLite.DifficultyLevel != null)
                {
                    this.DifficultyLevel = new DifficultyLevel(puzzleLite.DifficultyLevel);
                }
                // Link the primary key to the base Id field.
                SetPrimaryKey(PuzzleId);
            }
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="PuzzleBase"/> class.
        /// Initializes a new empty instance of the PuzzleBase class from a DataRow with the Puzzle columns specified.
        /// </summary>
        /// <param name="record">A dynamic Expando Object.</param>
        /// <param name="columnsToInclude">A list of <see cref="Enumerations.PuzzleProperty"/> if you want a sub set of properties populated.  Defaulted to null which will be translated to mean no filter and return all properties.</param>
        public PuzzleBase(ExpandoObject record, List<Enumerations.PuzzleProperty> columnsToInclude = null)
        {
            if (record != null)
            {
                IDictionary<string, object> recordAsDictionary = (IDictionary<string, object>)record;

                Initialize();

                // If not specified, default to all columns.
                if (columnsToInclude == null)
                {
                    columnsToInclude = new List<Enumerations.PuzzleProperty>() { Enumerations.PuzzleProperty.All };
                }
                else if (!columnsToInclude.Contains(Enumerations.PuzzleProperty.All))
                {
                    // Primary key must always be passed.
                    PuzzleId = recordAsDictionary.ValueAs<int?>("PuzzleId");
                }

                if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.PuzzleCode))
                {
                    PuzzleCode = recordAsDictionary.ValueAs<Guid>("PuzzleCode");
                }
                if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.BoardId))
                {
                    BoardId = recordAsDictionary.ValueAs<int?>("BoardId");
                }
                if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.DifficultyLevelId))
                {
                    DifficultyLevelId = recordAsDictionary.ValueAs<int?>("DifficultyLevelId");
                }
                if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.Path))
                {
                    Path = recordAsDictionary.ValueAs<string>("Path");
                }
                if (columnsToInclude.Contains(Enumerations.PuzzleProperty.All) || columnsToInclude.Contains(Enumerations.PuzzleProperty.PuzzleOfTheDayDate))
                {
                    PuzzleOfTheDayDate = recordAsDictionary.ValueAs<DateTime?>("PuzzleOfTheDayDate");
                }

                // Link the primary key to the base Id field.
                SetPrimaryKey(PuzzleId.Value);
            }
        }
        #endregion Constructor(s)

        #region Declarations
        KnightsTour.CoreLibrary.IStorageHandler storageHandler = null; // Storage handler reference used for lazy loading.
        KnightsTour.Board _board = null; // Private Board (by BoardId) reference used for graph hydraion.  Lazy loaded if not initialized explicitly.
        KnightsTour.DifficultyLevel _difficultyLevel = null; // Private DifficultyLevel (by DifficultyLevelId) reference used for graph hydraion.  Lazy loaded if not initialized explicitly.
        IEnumerable<KnightsTour.Solution> _solutions = null; // Private collection of child solutions references (by PuzzleId) used for graph hydration.  Lazy loaded if not initialized explicitly.
        #endregion Declarations

        #region Properties

        /// <summary>
        /// The override implementation of the base Id interface property.
        /// </summary>
        /// <value>
        /// The id.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public new int? Id
        {
            get
            {
                return PuzzleId;
            }
            set
            {
                PuzzleId = value;
            }
        }

        /// <summary>
        /// Gets or sets the related Board (by BoardId) entity reference.  Lazy loaded unless specified.
        /// </summary>
        /// <value>
        /// The board.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public new KnightsTour.Board Board
        {
            get
            {
                if ((_board == null || _board.IsNew) && BoardId.HasValue)
                {
                    _board = BoardId.HasValue ? new BoardLogic(StorageHandler, UserName).GetById(BoardId.Value) : new Board();
                }
                return _board;
            }
            set
            {
                _board = value;
            }
        }

        /// <summary>
        /// Gets or sets the related DifficultyLevel (by DifficultyLevelId) entity reference.  Lazy loaded unless specified.
        /// </summary>
        /// <value>
        /// The difficulty level.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public new KnightsTour.DifficultyLevel DifficultyLevel
        {
            get
            {
                if ((_difficultyLevel == null || _difficultyLevel.IsNew) && DifficultyLevelId.HasValue)
                {
                    _difficultyLevel = DifficultyLevelId.HasValue ? new DifficultyLevelLogic(StorageHandler, UserName).GetById(DifficultyLevelId.Value) : new DifficultyLevel();
                }
                return _difficultyLevel;
            }
            set
            {
                _difficultyLevel = value;
            }
        }

        /// <summary>
        /// Gets or sets the collection of child solutions references (by PuzzleId) used for graph hydration.  Lazy loaded if not initialized explicitly.
        /// </summary>
        /// <value>
        /// The solutions.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public IEnumerable<KnightsTour.Solution> Solutions
        {
            get
            {
                if (_solutions == null)
                {
                    _solutions = new List<Solution>();
                    if (!IsNew)
                    {
                        _solutions = new SolutionLogic(StorageHandler, UserName).GetByFK<int?>(EntityMapper.GetPropertyName(Enumerations.SolutionProperty.PuzzleId).ToString(), PuzzleId);
                    }
                }
                return _solutions;
            }
            set
            {
                _solutions = value;
            }
        }

        /// <summary>
        /// The primary key column for this entity.
        /// </summary>
        /// <value>
        /// The primary key.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public Enumerations.PuzzleProperty PrimaryKey
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the field validations.
        /// </summary>
        /// <value>
        /// The field validations.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public List<FieldValidator> FieldValidations
        {
            get;
            set;
        }

        /// <summary>
        /// The insert header for bulk SQL operations.
        /// </summary>
        /// <value>
        /// The s q l insert bulk header.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public string SQLInsertBulkHeader
        {
            get
            {
                if (PKInsertConfiguration == KnightsTour.CoreLibrary.Enumerations.InsertPKRule.AutoIncrement)
                {
                    return $"INSERT INTO {StorageProvider.GetTableSQL(EntityMapper.EntityNameTransformation[EntityName], TableSchema)} ({StorageProvider.GetColumnSQL("PuzzleCode")}, {StorageProvider.GetColumnSQL("BoardId")}, {StorageProvider.GetColumnSQL("DifficultyLevelId")}, {StorageProvider.GetColumnSQL("Path")}, {StorageProvider.GetColumnSQL("PuzzleOfTheDayDate")})";
                }
                else
                {
                    return $"INSERT INTO {StorageProvider.GetTableSQL(EntityMapper.EntityNameTransformation[EntityName], TableSchema)} ({StorageProvider.GetColumnSQL("PuzzleCode")}, {StorageProvider.GetColumnSQL("BoardId")}, {StorageProvider.GetColumnSQL("DifficultyLevelId")}, {StorageProvider.GetColumnSQL("Path")}, {StorageProvider.GetColumnSQL("PuzzleOfTheDayDate")})";
                }
            }
        }

        /// <summary>
        /// The SQL safe insert row for bulk SQL operations.
        /// </summary>
        /// <value>
        /// The s q l insert bulk row.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public string SQLInsertBulkRow
        {
            get
            {
                if (PKInsertConfiguration == KnightsTour.CoreLibrary.Enumerations.InsertPKRule.AutoIncrement)
                {
                    return $"({PuzzleCode.SafeSQL()}, {BoardId.SafeSQL()}, {DifficultyLevelId.SafeSQL()}, {Path.SafeSQL()}, {PuzzleOfTheDayDate.SafeSQL()})";
                }
                else if (PKInsertConfiguration == KnightsTour.CoreLibrary.Enumerations.InsertPKRule.Manual)
                {
                    return $"({PuzzleId.SafeSQL()}, {PuzzleCode.SafeSQL()}, {BoardId.SafeSQL()}, {DifficultyLevelId.SafeSQL()}, {Path.SafeSQL()}, {PuzzleOfTheDayDate.SafeSQL()})";
                }
                else if (PKInsertConfiguration == KnightsTour.CoreLibrary.Enumerations.InsertPKRule.Sequence)
                {
                    return $"({StorageProvider.GetTableSQL(EntityMapper.SequenceMapper[EntityName], TableSchema)}.NEXTVAL, {PuzzleCode.SafeSQL()}, {BoardId.SafeSQL()}, {DifficultyLevelId.SafeSQL()}, {Path.SafeSQL()}, {PuzzleOfTheDayDate.SafeSQL()})";
                }
                else
                {
                    throw new Exception($"Unhandled PK Insert Configuration: {StorageHandler.PKInsertConfiguration.ToString()}");
                }
            }
        }

        /// <summary>
        /// The insert SQL statement for single records.
        /// </summary>
        /// <value>
        /// The s q l insert statement.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public KnightsTour.CoreLibrary.IStorageStatement SQLInsertStatement
        {
            get
            {
                KnightsTour.CoreLibrary.StorageStatement statement = new KnightsTour.CoreLibrary.StorageStatement();

                if (KnightsTour.Context.UseStoredProcedureIntegration)
                {
                    statement.CommandType = System.Data.CommandType.StoredProcedure;
                    statement.Statement = GetStoredProcedureName(KnightsTour.CoreLibrary.Enumerations.StoredProcedureType.Insert);
                    statement.Parameters = new List<KnightsTour.CoreLibrary.IParameter>
                    {
                        new KnightsTour.CoreLibrary.GenericParameter($"{StorageProvider.GetParameterPrefix()}BoardId", GetDBValue(KnightsTour.Enumerations.PuzzleProperty.BoardId)),
                        new KnightsTour.CoreLibrary.GenericParameter($"{StorageProvider.GetParameterPrefix()}DifficultyLevelId", GetDBValue(KnightsTour.Enumerations.PuzzleProperty.DifficultyLevelId)),
                        new KnightsTour.CoreLibrary.GenericParameter($"{StorageProvider.GetParameterPrefix()}Path", GetDBValue(KnightsTour.Enumerations.PuzzleProperty.Path)),
                        new KnightsTour.CoreLibrary.GenericParameter($"{StorageProvider.GetParameterPrefix()}PuzzleOfTheDayDate", GetDBValue(KnightsTour.Enumerations.PuzzleProperty.PuzzleOfTheDayDate)),
                    };
                }
                else
                {
                    StringBuilder sql = new StringBuilder(SQLInsertBulkHeader);

                    sql.Append(" VALUES(");
                    foreach (Enumerations.PuzzlePropertyNotComputed property in Enum.GetValues(typeof(Enumerations.PuzzlePropertyNotComputed)))
                    {
                        if (property != Enumerations.PuzzlePropertyNotComputed.All)
                        {
                            if (ConvertProperty(property) != PrimaryKey)
                            {
                                sql.Append($"{StorageProvider.GetParameterPrefix()}{property.ToString()}, ");
                                statement.Parameters.Add(new KnightsTour.CoreLibrary.GenericParameter(StorageProvider.GetParameterPrefix() + property.ToString(), GetDBValue(property), GetDataType(property)));
                            }
                            else if (PKInsertConfiguration == KnightsTour.CoreLibrary.Enumerations.InsertPKRule.Sequence)
                            {
                                sql.Append($"{EntityMapper.GetSequenceName(EntityName)}.NEXTVAL, ");
                            }
                            else if (PKInsertConfiguration == KnightsTour.CoreLibrary.Enumerations.InsertPKRule.Manual)
                            {
                                sql.Append($"{StorageProvider.GetParameterPrefix()}{property.ToString()}, ");
                                statement.Parameters.Add(new KnightsTour.CoreLibrary.GenericParameter(StorageProvider.GetParameterPrefix() + property.ToString(), GetDBValue(property), GetDataType(property)));
                            }
                        }
                    }

                    // Remove the trailing comma and space.
                    sql = sql.Remove(sql.Length - 2, 2);
                    sql.Append(")");

                    statement.Statement = sql.ToString();
                }

                return statement;
            }
        }

        /// <summary>
        /// The update SQL statement for single records.
        /// </summary>
        /// <value>
        /// The s q l update statement.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public KnightsTour.CoreLibrary.IStorageStatement SQLUpdateStatement
        {
            get
            {
                KnightsTour.CoreLibrary.StorageStatement statement = new KnightsTour.CoreLibrary.StorageStatement();

                if (KnightsTour.Context.UseStoredProcedureIntegration)
                {
                    statement.CommandType = System.Data.CommandType.StoredProcedure;
                    statement.Statement = GetStoredProcedureName(KnightsTour.CoreLibrary.Enumerations.StoredProcedureType.Update);
                    statement.Parameters = new List<KnightsTour.CoreLibrary.IParameter>
                    {
                        new KnightsTour.CoreLibrary.GenericParameter($"{StorageProvider.GetParameterPrefix()}PuzzleId", GetDBValue(KnightsTour.Enumerations.PuzzleProperty.PuzzleId)),
                        new KnightsTour.CoreLibrary.GenericParameter($"{StorageProvider.GetParameterPrefix()}PuzzleCode", GetDBValue(KnightsTour.Enumerations.PuzzleProperty.PuzzleCode)),
                        new KnightsTour.CoreLibrary.GenericParameter($"{StorageProvider.GetParameterPrefix()}BoardId", GetDBValue(KnightsTour.Enumerations.PuzzleProperty.BoardId)),
                        new KnightsTour.CoreLibrary.GenericParameter($"{StorageProvider.GetParameterPrefix()}DifficultyLevelId", GetDBValue(KnightsTour.Enumerations.PuzzleProperty.DifficultyLevelId)),
                        new KnightsTour.CoreLibrary.GenericParameter($"{StorageProvider.GetParameterPrefix()}Path", GetDBValue(KnightsTour.Enumerations.PuzzleProperty.Path)),
                        new KnightsTour.CoreLibrary.GenericParameter($"{StorageProvider.GetParameterPrefix()}PuzzleOfTheDayDate", GetDBValue(KnightsTour.Enumerations.PuzzleProperty.PuzzleOfTheDayDate)),
                    };
                }
                else
                {
                    StringBuilder sql = new StringBuilder($"UPDATE {StorageProvider.GetTableSQL(EntityMapper.EntityNameTransformation[EntityName], TableSchema)} SET ");

                    foreach (Enumerations.PuzzlePropertyNotComputed property in Enum.GetValues(typeof(Enumerations.PuzzlePropertyNotComputed)))
                    {
                        if (property != Enumerations.PuzzlePropertyNotComputed.All)
                        {
                            if (IsModified(ConvertProperty(property)))
                            {
                                sql.Append($"{StorageProvider.GetColumnSQL(EntityMapper.GetPropertyName(ConvertProperty(property)))} = {StorageProvider.GetParameterPrefix()}{property.ToString()}, ");
                                statement.Parameters.Add(new KnightsTour.CoreLibrary.GenericParameter(StorageProvider.GetParameterPrefix() + property.ToString(), GetDBValue(property), GetDataType(property)));
                            }
                        }
                    }

                    sql = sql.Remove(sql.Length - 2, 2); //Remove the trailing comma and space
                    sql.Append($" WHERE {StorageProvider.GetColumnSQL(PrimaryKeyField)} = {PuzzleId.SafeSQL()}");

                    statement.Statement = sql.ToString();
                }

                return statement;
            }
        }

        /// <summary>
        /// Gets or sets the initial state for this entity.
        /// </summary>
        /// <value>
        /// The initial state.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public PuzzleLiteBase InitialState
        {
            get;
            set;
        }

        /// <summary>
        /// Gets a value indicating whether this Puzzle instance is new or not.
        /// </summary>
        /// <value>
        /// The is new.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public bool IsNew
        {
            get
            {
                return !PuzzleId.HasValue;
            }
        }

        /// <summary>
        /// Gets the related name of the actual database table.
        /// </summary>
        /// <value>
        /// The table name.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public string TableName
        {
            get
            {
                return EntityMapper.GetDbEntityName(EntityName);
            }
        }

        /// <summary>
        /// Gets the related name of the actual database schema.
        /// </summary>
        /// <value>
        /// The table schema.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public string TableSchema
        {
            get
            {
                return "dbo";
            }
        }

        /// <summary>
        /// Gets the primary key default value.
        /// </summary>
        /// <value>
        /// The p k default value.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public string PKDefaultValue
        {
            get
            {
                return "";
            }
        }

        /// <summary>
        /// Gets or sets the storage handler from the default configured source unless otherwise set.
        /// </summary>
        /// <value>
        /// The storage handler.
        /// </value>
        [JsonIgnore]
        [XmlIgnore]
        public KnightsTour.CoreLibrary.IStorageHandler StorageHandler
        {
            get
            {
                if (storageHandler == null)
                {
                    storageHandler = StorageProvider.GetHandler();
                }
                return storageHandler;
            }
            set
            {
                storageHandler = value;
            }
        }

        /// <summary>
        /// The configured label or label collection configured, or the PK number or (new) if a new record.
        /// </summary>
        /// <value>
        /// The instance label.
        /// </value>
        public string InstanceLabel
        {
            get
            {
                if (IsNew)
                {
                    return "(New)";
                }
                else
                {
                    return PuzzleId.Value.ToString();
                }
            }
        }

        /// <summary>
        /// Returns the PuzzleOfTheDayDate formatted with either the projects default date format or the custom property date format if defined.
        /// </summary>
        /// <value>
        /// The puzzle of the day date formatted.
        /// </value>
        public string PuzzleOfTheDayDateFormatted
        {
            get
            {
                if (PuzzleOfTheDayDate.HasValue)
                {
                    return PuzzleOfTheDayDate.Value.ToString("yyyy-MM-dd");
                }
                else
                {
                    return string.Empty;
                }
            }
        }
        #endregion Properties

        #region Methods

        /// <summary>
        /// Validates the object using the defined field validators.
        /// </summary>
        public KnightsTour.CoreLibrary.IActionResponse Validate()
        {
            return KnightsTour.Context.ValidationHandler.ValidateEntity<int?>(Enumerations.EntityName.Puzzle.ToString(), TableSchema, this, IsNew);
        }

        /// <summary>
        /// Sets the original properties (required for object state checking).
        /// </summary>
        public void SetOriginalProperties()
        {
            InitialState = new PuzzleLite(this);
        }

        /// <summary>
        /// Serializes the object based on the defined serialization strategy defined in the <seealso cref="AuditHandler" />.
        /// </summary>
        /// <returns>System.String.</returns>
        /// <exception cref="NotImplementedException"></exception>
        public string SerializeObject()
        {
            string objectSerialization = string.Empty;
            switch (KnightsTour.Context.AuditHandler.SerializationStrategy)
            {
                case KnightsTour.CoreLibrary.Enumerations.SerializationStrategy.XML:
                    objectSerialization = KnightsTour.CoreLibrary.XMLAssistant.Serialize(ToDynamic());
                    break;
                case KnightsTour.CoreLibrary.Enumerations.SerializationStrategy.JSON:
                    objectSerialization = ToDynamic().ToString();
                    break;
                default:
                    throw new NotImplementedException($"{KnightsTour.Context.AuditHandler.SerializationStrategy.ToString()} serialization strategy not implemented.");
            }
            return objectSerialization;
        }

        /// <summary>
        /// Serializes the object differential based on the defined serialization strategy defined in the <seealso cref="AuditHandler" />.
        /// </summary>
        /// <returns>System.String.</returns>
        /// <exception cref="NotImplementedException"></exception>
        public string SerializeDifferential()
        {
            string objectSerialization = string.Empty;
            switch (KnightsTour.Context.AuditHandler.SerializationStrategy)
            {
                case KnightsTour.CoreLibrary.Enumerations.SerializationStrategy.XML:
                    objectSerialization = KnightsTour.CoreLibrary.XMLAssistant.Serialize(ToDynamic(KnightsTour.CoreLibrary.Enumerations.DynamicObjectStrategy.ModifiedPropertiesOnly));
                    break;
                case KnightsTour.CoreLibrary.Enumerations.SerializationStrategy.JSON:
                    objectSerialization = ToDynamic(KnightsTour.CoreLibrary.Enumerations.DynamicObjectStrategy.ModifiedPropertiesOnly).ToString();
                    break;
                default:
                    throw new NotImplementedException($"{KnightsTour.Context.AuditHandler.SerializationStrategy.ToString()} serialization strategy not implemented.");
            }
            return objectSerialization;
        }

        /// <summary>
        /// Creates a dynamic object based on the passed <seealso cref="KnightsTour.CoreLibrary.Enumerations.DynamicObjectStrategy" />.
        /// </summary>
        /// <param name="strategy">The strategy.</param>
        /// <returns>dynamic.</returns>
        /// <exception cref="NotImplementedException"></exception>
        public dynamic ToDynamic(KnightsTour.CoreLibrary.Enumerations.DynamicObjectStrategy strategy = KnightsTour.CoreLibrary.Enumerations.DynamicObjectStrategy.AllProperties)
        {
            dynamic dynamicPuzzle = new JObject();
            switch (strategy)
            {
                case KnightsTour.CoreLibrary.Enumerations.DynamicObjectStrategy.AllProperties:
                    dynamicPuzzle.PuzzleId = PuzzleId;
                    dynamicPuzzle.PuzzleCode = PuzzleCode;
                    dynamicPuzzle.BoardId = BoardId;
                    dynamicPuzzle.DifficultyLevelId = DifficultyLevelId;
                    dynamicPuzzle.Path = Path;
                    dynamicPuzzle.PuzzleOfTheDayDate = PuzzleOfTheDayDate;
                    break;
                case KnightsTour.CoreLibrary.Enumerations.DynamicObjectStrategy.AllPropertiesWithOriginals:
                    dynamicPuzzle.PuzzleId = PuzzleId;
                    dynamicPuzzle.PuzzleId_Original = InitialState.PuzzleId;
                    dynamicPuzzle.PuzzleCode = PuzzleCode;
                    dynamicPuzzle.PuzzleCode_Original = InitialState.PuzzleCode;
                    dynamicPuzzle.BoardId = BoardId;
                    dynamicPuzzle.BoardId_Original = InitialState.BoardId;
                    dynamicPuzzle.DifficultyLevelId = DifficultyLevelId;
                    dynamicPuzzle.DifficultyLevelId_Original = InitialState.DifficultyLevelId;
                    dynamicPuzzle.Path = Path;
                    dynamicPuzzle.Path_Original = InitialState.Path;
                    dynamicPuzzle.PuzzleOfTheDayDate = PuzzleOfTheDayDate;
                    dynamicPuzzle.PuzzleOfTheDayDate_Original = InitialState.PuzzleOfTheDayDate;
                    break;
                case KnightsTour.CoreLibrary.Enumerations.DynamicObjectStrategy.ModifiedPropertiesOnly:
                    if (IsModified(Enumerations.PuzzleProperty.PuzzleId))
                    {
                        dynamicPuzzle.PuzzleId = PuzzleId;
                        dynamicPuzzle.PuzzleId_Original = InitialState.PuzzleId;
                    }
                    if (IsModified(Enumerations.PuzzleProperty.PuzzleCode))
                    {
                        dynamicPuzzle.PuzzleCode = PuzzleCode;
                        dynamicPuzzle.PuzzleCode_Original = InitialState.PuzzleCode;
                    }
                    if (IsModified(Enumerations.PuzzleProperty.BoardId))
                    {
                        dynamicPuzzle.BoardId = BoardId;
                        dynamicPuzzle.BoardId_Original = InitialState.BoardId;
                    }
                    if (IsModified(Enumerations.PuzzleProperty.DifficultyLevelId))
                    {
                        dynamicPuzzle.DifficultyLevelId = DifficultyLevelId;
                        dynamicPuzzle.DifficultyLevelId_Original = InitialState.DifficultyLevelId;
                    }
                    if (IsModified(Enumerations.PuzzleProperty.Path))
                    {
                        dynamicPuzzle.Path = Path;
                        dynamicPuzzle.Path_Original = InitialState.Path;
                    }
                    if (IsModified(Enumerations.PuzzleProperty.PuzzleOfTheDayDate))
                    {
                        dynamicPuzzle.PuzzleOfTheDayDate = PuzzleOfTheDayDate;
                        dynamicPuzzle.PuzzleOfTheDayDate_Original = InitialState.PuzzleOfTheDayDate;
                    }
                    break;
                default:
                    throw new NotImplementedException($"{strategy.ToString()} strategy not implemented.");
            }
            return dynamicPuzzle;
        }

        /// <summary>
        /// Determines whether this instance is modified.
        /// </summary>
        /// <returns><c>true</c> if this instance is modified; otherwise, <c>false</c>.</returns>
        public bool IsModified()
        {
            foreach (Enumerations.PuzzleProperty property in Enum.GetValues(typeof(Enumerations.PuzzleProperty)))
            {
                if (property != Enumerations.PuzzleProperty.All)
                {
                    if (IsModified(property))
                    return true;
                }
            }
            return false;
        }

        /// <summary>
        /// Determines whether the specified property is modified.
        /// </summary>
        /// <param name="property">The Puzzle property to test.</param>
        /// <returns><c>true</c> if the specified property is modified; otherwise, <c>false</c>.</returns>
        /// <exception cref="NotImplementedException"></exception>
        public bool IsModified(Enumerations.PuzzleProperty property)
        {
            switch (property)
            {
                case Enumerations.PuzzleProperty.PuzzleId:
                    return PuzzleId != InitialState.PuzzleId;
                case Enumerations.PuzzleProperty.PuzzleCode:
                    return PuzzleCode != InitialState.PuzzleCode;
                case Enumerations.PuzzleProperty.BoardId:
                    return BoardId != InitialState.BoardId;
                case Enumerations.PuzzleProperty.DifficultyLevelId:
                    return DifficultyLevelId != InitialState.DifficultyLevelId;
                case Enumerations.PuzzleProperty.Path:
                    return Path != InitialState.Path;
                case Enumerations.PuzzleProperty.PuzzleOfTheDayDate:
                    return PuzzleOfTheDayDate != InitialState.PuzzleOfTheDayDate;
                case Enumerations.PuzzleProperty.All:
                    return IsModified();
                default:
                    throw new NotImplementedException($"{property.ToString()} property not implemented.");
            }
        }

        /// <summary>
        /// Initializes the properties of this class.
        /// </summary>
        public void Initialize()
        {
            MethodWrappers.CommonWrapper(baseInitialize, KnightsTour.CoreLibrary.Enumerations.ApplicationTier.Business, new object[] { });
        }

        /// <summary>
        /// The privately wrapped implementation of the Initialize method.
        /// </summary>
        /// <param name="arguments">The generic arguments sent to this method from the public wrapped call.</param>
        private void baseInitialize(object[] arguments)
        {
            InitialState = new PuzzleLite();

            // Base Entity properties.
            EntityName = Enumerations.EntityName.Puzzle.ToString();
            PrimaryKey = Enumerations.PuzzleProperty.PuzzleId;
            PrimaryKeyField = EntityMapper.GetPropertyName(PrimaryKey);
            PrimaryKeyFieldFormatted = "PuzzleId";
            PKInsertConfiguration = KnightsTour.CoreLibrary.Enumerations.InsertPKRule.AutoIncrement;

            // Table properties.
            PuzzleId = null;
            PuzzleCode = Guid.NewGuid();
            BoardId = null;
            DifficultyLevelId = null;
            Path = string.Empty;
            PuzzleOfTheDayDate = null;
        }

        /// <summary>
        /// Clones this instance.
        /// </summary>
        /// <returns>A cloned Puzzle.</returns>
        public Puzzle Clone()
        {
            Puzzle puzzle = new Puzzle();

            puzzle.PuzzleId = PuzzleId;
            puzzle.PuzzleCode = PuzzleCode;
            puzzle.BoardId = BoardId;
            puzzle.DifficultyLevelId = DifficultyLevelId;
            puzzle.Path = Path;
            puzzle.PuzzleOfTheDayDate = PuzzleOfTheDayDate;

            return puzzle;
        }

        /// <summary>
        /// Returns a readable summary of this object.
        /// </summary>
        /// <returns>System.String.</returns>
        public override string ToString()
        {
            return SerializeObject();
        }

        /// <summary>
        /// Converts a non computed property to a regular property.
        /// </summary>
        /// <param name="property">The non computed Puzzle property to convert.</param>
        /// <returns>The regular related property value.</returns>
        /// <exception cref="ArgumentException"></exception>
        private Enumerations.PuzzleProperty ConvertProperty(Enumerations.PuzzlePropertyNotComputed property)
        {
            foreach (Enumerations.PuzzleProperty regularProperty in Enum.GetValues(typeof(Enumerations.PuzzleProperty)))
            {
                if (regularProperty.ToString() == property.ToString())
                {
                    return regularProperty;
                }
            }

            throw new Exception($"Unable to convert non computed property '{property.ToString()}' of type 'PuzzlePropertyNotComputed' to a 'PuzzleProperty'.");
        }

        /// <summary>
        /// Returns the underlying object value.
        /// </summary>
        /// <param name="property">The not computed Puzzle property to test.</param>
        /// <returns>The dynamic underlying property value.</returns>
        /// <exception cref="ArgumentException"></exception>
        public dynamic GetDBValue(Enumerations.PuzzlePropertyNotComputed property)
        {
            return GetDBValue(ConvertProperty(property));
        }

        /// <summary>
        /// Returns the underlying object data type for this language.
        /// </summary>
        /// <param name="property">The non computed Puzzle property to test.</param>
        /// <returns>The data type for this property.</returns>
        /// <exception cref="ArgumentException"></exception>
        private string GetDataType(Enumerations.PuzzlePropertyNotComputed property)
        {
            return GetDataType(ConvertProperty(property));
        }

        /// <summary>
        /// Returns the underlying object value.
        /// </summary>
        /// <param name="property">The Puzzle property to test.</param>
        /// <returns>The dynamic underlying property value.</returns>
        /// <exception cref="ArgumentException"></exception>
        public dynamic GetDBValue(Enumerations.PuzzleProperty property)
        {
            switch (property)
            {
                case Enumerations.PuzzleProperty.PuzzleId:
                    if (PuzzleId == null) return DBNull.Value;
                    return PuzzleId;
                case Enumerations.PuzzleProperty.PuzzleCode:
                    return PuzzleCode;
                case Enumerations.PuzzleProperty.BoardId:
                    if (BoardId == null) return DBNull.Value;
                    return BoardId;
                case Enumerations.PuzzleProperty.DifficultyLevelId:
                    if (DifficultyLevelId == null) return DBNull.Value;
                    return DifficultyLevelId;
                case Enumerations.PuzzleProperty.Path:
                    if (Path == null) return DBNull.Value;
                    return Path;
                case Enumerations.PuzzleProperty.PuzzleOfTheDayDate:
                    if (PuzzleOfTheDayDate == null) return DBNull.Value;
                    return PuzzleOfTheDayDate;
                default:
                    throw new ArgumentException($"Property {property.ToString()} unhandled.");
            }
        }

        /// <summary>
        /// Returns the underlying object data type for this language.
        /// </summary>
        /// <param name="property">The Puzzle property to test.</param>
        /// <returns>The data type for this property.</returns>
        /// <exception cref="ArgumentException"></exception>
        private string GetDataType(Enumerations.PuzzleProperty property)
        {
            switch (property)
            {
                case Enumerations.PuzzleProperty.PuzzleId:
                    return "int?";
                case Enumerations.PuzzleProperty.PuzzleCode:
                    return "Guid";
                case Enumerations.PuzzleProperty.BoardId:
                    return "int?";
                case Enumerations.PuzzleProperty.DifficultyLevelId:
                    return "int?";
                case Enumerations.PuzzleProperty.Path:
                    return "string";
                case Enumerations.PuzzleProperty.PuzzleOfTheDayDate:
                    return "DateTime?";
                default:
                    throw new ArgumentException($"Property {property.ToString()} unhandled.");
            }
        }

        /// <summary>
        /// Sets the primary key.
        /// </summary>
        /// <param name="id">The Puzzles primary key value.</param>
        public void SetPrimaryKey(int? id)
        {
            PuzzleId = id;
            Id = id;
            SetOriginalProperties();
        }

        /// <summary>
        /// Updates the individual properties from the lite object.
        /// </summary>
        /// <param name="puzzleLite">The PuzzleLite source object.</param>
        public void UpdateFromLite(PuzzleLite puzzleLite)
        {
            // Do this first just to make sure.
            SetOriginalProperties();

            PuzzleId = puzzleLite.PuzzleId;
            PuzzleCode = puzzleLite.PuzzleCode;
            BoardId = puzzleLite.BoardId;
            DifficultyLevelId = puzzleLite.DifficultyLevelId;
            Path = puzzleLite.Path;
            PuzzleOfTheDayDate = puzzleLite.PuzzleOfTheDayDate;
        }

        /// <summary>
        /// Returns the stored procedure name (of a given type) or this class.
        /// </summary>
        /// <param name="type">The stored procedure type.</param>
        public string GetStoredProcedureName(KnightsTour.CoreLibrary.Enumerations.StoredProcedureType type)
        {
            string storedProcedureName = string.Empty;

            // The Stored procedure prefix (as defined on the model) is optional, deal with that first.
            if (!string.IsNullOrEmpty(Schema.Model.StoredProcedurePrefix))
            {
                storedProcedureName += $"{Schema.Model.StoredProcedurePrefix}_";
            }

            // Model prefix (optional), entity name then finally the type.
            if (string.IsNullOrEmpty(TableSchema))
            {
                return $"{storedProcedureName}{TextAssistant.PascalCase(OnlyAlpha(TableName, true))}_{type}";
            }
            else
            {
                return $"{TableSchema}.{storedProcedureName}{TextAssistant.PascalCase(OnlyAlpha(TableName, true))}_{type}";
            }
        }
        #endregion Methods

    } // Class
} // Namespace