// © 2023 27 Software
//
// ************************************************************************
// Author           : DXterity8 Version 8.6
// Created          : January 13, 2023 7:25:01 AM
// File             : Puzzle.cs
// ************************************************************************

using System;
using System.Collections.Generic;
using System.Data;

namespace KnightsTour
{
    /// <summary>
    /// The extended Puzzle object.
    /// Generated On: January 13, 2023 at 7:25:01 AM by DXterity Solutions.
    /// Generated By: DXterity8 Version 8.6.0 (see https://dxteritysolutions.com/).
    /// </summary>
    /// <remarks>
    /// Feel free to add properties as you see fit here.
    /// In general operations against or for Puzzles should be placed in the PuzzleLogic class.
    /// The exception to this suggestion is overriding base methods (Initialize is a common example)
    /// e.g. public new void Initialize(){ base.Initialize(); }
    /// </remarks>
    public class Puzzle : PuzzleBase
    {
        #region Extended Constructor(s)

        /// <summary>
        /// Initializes a new instance of the <see cref="Puzzle"/> class.
        /// Initializes a new empty instance of the Puzzle class.
        /// </summary>
        /// <example>
        /// <code>
        /// Puzzle puzzle = new Puzzle();
        /// </code>
        /// </example>
        public Puzzle() : base()
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="Puzzle"/> class.
        /// Initializes a new empty instance of the Puzzle class with the given primary key.
        /// </summary>
        /// <param name="id">The primary key value.</param>
        /// <example>
        /// <code>
        /// Puzzle puzzle = new Puzzle(1);
        /// </code>
        /// </example>
        public Puzzle(int? id) : base(id)
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="Puzzle"/> class.
        /// Initializes a new empty instance of the Puzzle class from the record in a data reader.
        /// </summary>
        /// <param name="record">A record returned from a database reader.</param>
        public Puzzle(IDataRecord record) : base(record, null)
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="Puzzle"/> class.
        /// Initializes a new empty instance of the Puzzle class from the record in a data reader populating only the Puzzle columns specified.
        /// </summary>
        /// <param name="record">A record returned from a database reader.</param>
        /// <param name="columnsToInclude">A list of <see cref="Enumerations.PuzzleProperty"/> if you want a sub set of properties populated.  Defaulted to null which will be translated to mean no filter and return all properties.</param>
        public Puzzle(IDataRecord record, List<Enumerations.PuzzleProperty> columnsToInclude = null) : base(record, columnsToInclude)
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="Puzzle"/> class.
        /// Initializes a new empty instance of the Puzzle class from a DataRow (via a <see cref="DataTable" /> usually part of a larger <see cref="DataSet" />).
        /// </summary>
        /// <param name="record">The <see cref="DataRow" />.</param>
        public Puzzle(DataRow record) : base(record, null)
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="Puzzle"/> class.
        /// Initializes a new empty instance of the Puzzle class from a DataRow (via a <see cref="DataTable" /> usually part of a larger <see cref="DataSet" />) populating only the Puzzle columns specified.
        /// </summary>
        /// <param name="record">The <see cref="DataRow" />.</param>
        /// <param name="columnsToInclude">A list of <see cref="Enumerations.PuzzleProperty"/> if you want a sub set of properties populated.  Defaulted to null which will be translated to mean no filter and return all properties.</param>
        public Puzzle(DataRow record, List<Enumerations.PuzzleProperty> columnsToInclude = null) : base(record, columnsToInclude)
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="Puzzle"/> class.
        /// Initializes a new empty instance of the Puzzle class from the lite version of the Puzzle entity.
        /// </summary>
        /// <param name="puzzleLite">An object representing the lite version of the Puzzle.</param>
        public Puzzle(PuzzleLite puzzleLite) : base(puzzleLite)
        {
        }
        #endregion Extended Constructor(s)

        #region Extended Declarations
        #endregion Extended Declarations

        #region Extended Properties
        #endregion Extended Properties

        #region Extended Methods
        #endregion Extended Methods

    } // Class
} // Namespace