// © 2023 27 Software
//
// ************************************************************************
// Author           : DXterity8 Version 8.6
// Created          : March 19, 2023 7:56:06 AM
// File             : EventHistoryLogicTestsBase.cs
// ************************************************************************

using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;

using KnightsTour;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace KnightsTourUnitTests.Entity
{
    /// <summary>
    /// Tests against the EventHistoryLogic support class.  Inherits <seealso cref="BaseDataTest" />
    /// Generated On: March 19, 2023 at 7:56:06 AM by DXterity Solutions.
    /// Generated By: DXterity8 Version 8.6.0 (see https://dxteritysolutions.com/).
    /// </summary>
    /// <remarks>
    /// This class will be regenerated when requested to stay in sync with your model.
    /// </remarks>
    [TestClass]
    public class EventHistoryLogicTestsBase : DataTestBase<int?>
    {
        #region EventHistory logic tests Methods

        /// <summary>
        /// Description for Event History Logic_ Has Repository.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_HasRepository()
        {
            KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);
            KnightsTour.CoreLibrary.IRepository<KnightsTour.EventHistory, KnightsTour.EventHistoryLite, int?> repository = logic.Repository;
            Assert.IsNotNull(repository);
        }

        /// <summary>
        /// Description for Event History Logic_ Has Storage Handler.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_HasStorageHandler()
        {
            KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);
            KnightsTour.CoreLibrary.IStorageHandler handler = logic.StorageHandler;
            Assert.IsNotNull(handler);
        }

        /// <summary>
        /// Description for Event History Logic_ Get By Id.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_GetById()
        {
            EntityRepository_GetById<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History Logic_ Get By Ids.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_GetByIds()
        {
            KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);
            if (GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.RecordCount) > 1)
            {
                int? firstId = GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.FirstId);
                int? lastId = GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.LastId);
                List<int?> ids = new List<int?>() { firstId, lastId };

                List<KnightsTour.EventHistory> eventHistories = logic.GetByIds(ids).ToList();
                Assert.IsNotNull(eventHistories);
                Assert.AreEqual(eventHistories.Count, 2);
                eventHistories = eventHistories.OrderBy(x => x.Id).ToList();
                Assert.AreEqual(eventHistories[0].Id, firstId);
                Assert.AreEqual(eventHistories[1].Id, lastId);
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Get All.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_GetAll()
        {
            KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);
            long totalRecords = GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.RecordCount);
            if (totalRecords > 0)
            {
                List<KnightsTour.EventHistory> eventHistories = logic.GetAll().ToList();
                Assert.IsTrue(eventHistories.Count > 0);
                Assert.IsTrue(eventHistories.Count >= totalRecords);
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Get All_ By Condition.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_GetAll_ByCondition()
        {
            KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);
            string pk = new KnightsTour.EventHistory().PrimaryKeyField;

            long totalRecords = GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.RecordCount);
            if (totalRecords > 1)
            {
                int? maxId = GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.LastId);
                List<KnightsTour.EventHistory> eventHistories = logic.GetAll(new KnightsTour.CoreLibrary.RetrievalCondition { SQLWhere = $"{StorageProvider.GetColumnSQL(pk)} < {maxId}" }).ToList();
                Assert.IsTrue(eventHistories.Count > 0);
                Assert.IsTrue(eventHistories.Count < totalRecords);
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Get All_ By Predicate.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_GetAll_ByPredicate()
        {
            long totalRecords = GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.RecordCount);
            if (totalRecords > 0)
            {
                KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);
                int? maxId = GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.LastId);
                EntityRepository_GetAll_ByPredicate<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(a => a.EventHistoryId < maxId);

                if (totalRecords > 1)
                {
                    List<KnightsTour.EventHistory> eventHistories = logic.GetAll(a => a.EventHistoryId < maxId).ToList();
                    Assert.IsTrue(eventHistories.Count > 0);
                    Assert.IsTrue(eventHistories.Count < totalRecords);
                }
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Get All_ By F K.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_GetAll_ByFK()
        {
            KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);
            foreach (string property in EntityMapper.FKNames(new KnightsTour.EventHistory().EntityName))
            {
                // Get some valid FK Values.
                foreach (int? fkValue in StorageProvider.GetFKValues<KnightsTour.EventHistory, KnightsTour.EventHistoryLite, int?>(property))
                {
                    List<KnightsTour.EventHistory> eventHistories = logic.GetByFK(property, fkValue, new KnightsTour.CoreLibrary.RetrievalCondition { SQLOrderBy = property, Skip = 0, Take = MaxFKQuantity }).ToList();
                    Assert.IsTrue(eventHistories.Count > 0);
                    Assert.IsTrue(eventHistories.Count <= MaxFKQuantity);
                }
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Get All_ By F Ks.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_GetAll_ByFKs()
        {
            if(StorageProvider.GetEntityAttribute<KnightsTour.EventHistory, KnightsTour.EventHistoryLite, int?>().RecordCount == 0)
            {
                Assert.Inconclusive("Unable to insert an entity of type 'event history' due to lack of data.");
            }

            KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);
            foreach (string property in EntityMapper.FKNames(new KnightsTour.EventHistory().EntityName))
            {
                // Get some valid FK Values.
                List<KnightsTour.EventHistory> eventHistories = logic.GetByFKs(property, KnightsTour.StorageProvider.GetFKValues<KnightsTour.EventHistory, KnightsTour.EventHistoryLite, int?>(property), new KnightsTour.CoreLibrary.RetrievalCondition { SQLOrderBy = property, Skip = 0, Take = MaxFKQuantity }).ToList();
                Assert.IsTrue(eventHistories.Count > 0);
                Assert.IsTrue(eventHistories.Count <= MaxFKQuantity);
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Insert_ Single.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_Insert_Single()
        {
            using (var transactionScope = new TransactionScope())
            {
                KnightsTour.EventHistory eventHistory = InsertEntity<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Insert_ Multiple.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_Insert_Multiple()
        {
            // Block size larger than the number of accounts.
            using (var transactionScope = new TransactionScope())
            {
                KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);

                List<KnightsTour.EventHistory> eventHistories = CreateEntities<KnightsTour.EventHistory>(BulkTestQuantity);

                Assert.IsNotNull(eventHistories);
                Assert.IsTrue(eventHistories.Count == BulkTestQuantity);
                foreach (KnightsTour.EventHistory eventHistory in eventHistories)
                {
                    Assert.IsTrue(eventHistory.IsNew);
                }

                // If the primary key insertion type is manual, then configure some values now.
                if (eventHistories[0].PKInsertConfiguration == KnightsTour.CoreLibrary.Enumerations.InsertPKRule.Manual)
                {
                    foreach (KnightsTour.EventHistory eventHistory in eventHistories)
                    {
                        eventHistory.Id = GetRandomValue<int?>();
                    }
                }

                KnightsTour.CoreLibrary.IActionResponse response = logic.Insert(eventHistories, 500);
                Assert.IsTrue(response.IsValid);

                // Block size less than the number of accounts.
                eventHistories = CreateEntities<KnightsTour.EventHistory>(BulkTestQuantity);

                Assert.IsNotNull(eventHistories);
                Assert.IsTrue(eventHistories.Count == BulkTestQuantity);
                foreach (KnightsTour.EventHistory eventHistory in eventHistories)
                {
                    Assert.IsTrue(eventHistory.IsNew);
                }

                // If the primary key insertion type is manual, then configure some values now.
                if (eventHistories[0].PKInsertConfiguration == KnightsTour.CoreLibrary.Enumerations.InsertPKRule.Manual)
                {
                    foreach (KnightsTour.EventHistory eventHistory in eventHistories)
                    {
                        eventHistory.Id = GetRandomValue<int?>();
                    }
                }

                response = logic.Insert(eventHistories, BulkTestQuantity - 1);
                Assert.IsTrue(response.IsValid);
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Update_ Single.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_Update_Single()
        {
            using (var transactionScope = new TransactionScope())
            {
                KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);

                #region Create and insert a new eventHistory
                KnightsTour.EventHistory eventHistory = InsertEntity<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
                #endregion

                #region Now let's update that newly created eventHistory
                if (GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.HasStringField))
                {
                    string stringField = GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.StringField);
                    string currentValue = KnightsTour.CoreLibrary.ReflectionAssistant.GetValue<KnightsTour.EventHistory, string>(eventHistory, stringField);
                    string newValue = "modified";
                    if (string.IsNullOrEmpty(currentValue))
                    {
                        newValue = currentValue + " modified.";
                        if (currentValue.StartsWith("a"))
                        {
                            newValue = currentValue.Replace("a", "z");
                        }
                    }
                    KnightsTour.CoreLibrary.ReflectionAssistant.SetValue<KnightsTour.EventHistory>(eventHistory, stringField, newValue);
                    KnightsTour.CoreLibrary.IActionResponse updateResponse = logic.Update(eventHistory);
                    Assert.IsTrue(updateResponse.IsValid);
                }
                else if (GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.HasIntField))
                {
                    string intField = GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.IntField);
                    int currentValue = KnightsTour.CoreLibrary.ReflectionAssistant.GetValue<KnightsTour.EventHistory, int>(eventHistory, intField);
                    int newValue = currentValue + 1;
                    KnightsTour.CoreLibrary.ReflectionAssistant.SetValue<KnightsTour.EventHistory>(eventHistory, intField, newValue);
                    KnightsTour.CoreLibrary.IActionResponse updateResponse = logic.Update(eventHistory);
                    Assert.IsTrue(updateResponse.IsValid);
                }
                #endregion
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Update_ Multiple.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_Update_Multiple()
        {
            using (var transactionScope = new TransactionScope())
            {
                KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);

                string pk = new KnightsTour.EventHistory().PrimaryKeyField;

                if (GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.RecordCount) > 0)
                {
                    List<KnightsTour.EventHistory> eventHistories = logic.GetAll(new KnightsTour.CoreLibrary.RetrievalCondition
                    {
                        SQLOrderBy = StorageProvider.GetColumnSQL(pk),
                        Skip = 0,
                        Take = BulkTestQuantity
                    }).ToList();

                    Assert.IsTrue(eventHistories.Count > 0);

                    // Modify each account.
                    bool modified = false;
                    foreach (KnightsTour.EventHistory eventHistory in eventHistories)
                    {
                        if (GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.HasStringField))
                        {
                            string stringField = GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.StringField);
                            string currentValue = KnightsTour.CoreLibrary.ReflectionAssistant.GetValue<KnightsTour.EventHistory, string>(eventHistory, stringField);
                            string newValue = "modified";
                            if (string.IsNullOrEmpty(currentValue))
                            {
                                newValue = currentValue + " modified.";
                                if (currentValue.StartsWith("a"))
                                {
                                    newValue = currentValue.Replace("a", "z");
                                }
                            }
                            KnightsTour.CoreLibrary.ReflectionAssistant.SetValue<KnightsTour.EventHistory>(eventHistory, stringField, newValue);
                            modified = true;
                        }
                        else if (GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.HasIntField))
                        {
                            string intField = GetEntityProperty<KnightsTour.EventHistory, EventHistoryLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.IntField);
                            int currentValue = KnightsTour.CoreLibrary.ReflectionAssistant.GetValue<KnightsTour.EventHistory, int>(eventHistory, intField);
                            int newValue = currentValue + 1;
                            KnightsTour.CoreLibrary.ReflectionAssistant.SetValue<KnightsTour.EventHistory>(eventHistory, intField, newValue);
                            modified = true;
                        }
                    }
                    if (modified)
                    {
                        KnightsTour.CoreLibrary.IActionResponse updateResponse = logic.Update(eventHistories);
                        Assert.IsTrue(updateResponse.IsValid);
                    }
                }
            }

        }

        /// <summary>
        /// Description for Event History Logic_ Delete By Id.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_DeleteById()
        {
            using (var transactionScope = new TransactionScope())
            {
                KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);

                #region Create and insert a new eventHistory
                KnightsTour.EventHistory eventHistory = InsertEntity<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
                #endregion

                #region Now let's delete that newly created eventHistory by it's id
                KnightsTour.CoreLibrary.IActionResponse deleteResponse = logic.Delete(eventHistory.Id.Value);
                Assert.IsTrue(deleteResponse.IsValid);
                #endregion
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Delete By Ids.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_DeleteByIds()
        {
            using (var transactionScope = new TransactionScope())
            {
                KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);

                #region Create and insert some new eventHistories
                List<int?> newIds = new List<int?>();
                for (int i = 0; i < BulkTestQuantity; i++)
                {
                    KnightsTour.EventHistory eventHistory = InsertEntity<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
                    newIds.Add(eventHistory.Id.Value);
                }
                Assert.IsTrue(newIds.Count == BulkTestQuantity);
                #endregion

                #region Now let's delete that newly cretaed eventHistory by it's id
                KnightsTour.CoreLibrary.IActionResponse deleteResponse = logic.Delete(newIds);
                Assert.IsTrue(deleteResponse.IsValid);
                #endregion
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Delete By Entity.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_DeleteByEntity()
        {
            using (var transactionScope = new TransactionScope())
            {
                KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);

                #region Create and insert a new eventHistory
                KnightsTour.EventHistory eventHistory = InsertEntity<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
                #endregion

                #region Now let's delete that newly created eventHistory by it's id
                KnightsTour.CoreLibrary.IActionResponse deleteResponse = logic.Delete(eventHistory);
                Assert.IsTrue(deleteResponse.IsValid);
                #endregion
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Delete By Entities.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_DeleteByEntities()
        {
            using (var transactionScope = new TransactionScope())
            {
                KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);

                #region Create and insert some new eventHistories
                List<KnightsTour.EventHistory> newEntities = new List<KnightsTour.EventHistory>();
                for (int i = 0; i < BulkTestQuantity; i++)
                {
                    KnightsTour.EventHistory eventHistory = InsertEntity<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
                    newEntities.Add(eventHistory);
                }
                Assert.IsTrue(newEntities.Count == BulkTestQuantity);
                #endregion

                #region Now let's delete that newly created eventHistory by it's id
                KnightsTour.CoreLibrary.IActionResponse deleteResponse = logic.Delete(newEntities);
                Assert.IsTrue(deleteResponse.IsValid);
                #endregion
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Delete_ Cascade.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_Delete_Cascade()
        {
            using (var transactionScope = new TransactionScope())
            {
                KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);

                #region Create and insert a new eventHistory
                KnightsTour.EventHistory eventHistory = InsertEntity<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
                #endregion

                #region Now let's delete that newly created eventHistory by it's id
                KnightsTour.CoreLibrary.IActionResponse deleteResponse = logic.DeleteCascade(eventHistory.Id.Value);
                Assert.IsTrue(deleteResponse.IsValid);
                #endregion
            }
        }

        /// <summary>
        /// Description for Event History Logic_ Delete_ By F K.
        /// </summary>
        [TestMethod]
        public void EventHistoryLogic_Delete_ByFK()
        {
            EntityMetaData meta = new EntityMetaData(KnightsTour.Enumerations.EntityName.EventHistory, UserName);

            if (meta.Dependencies.Count > 0)
            {
                Assert.Inconclusive("Delete by FK is not possible due to dependencies.");
            }
            else
            {
                KnightsTour.EventHistoryLogic logic = new KnightsTour.EventHistoryLogic(UserName);
                using (var transactionScope = new TransactionScope())
                {
                    foreach (string property in EntityMapper.FKNames(new KnightsTour.EventHistory().EntityName))
                    {
                        // Get some valid FK Values.
                        foreach (int fkValue in StorageProvider.GetFKValues<KnightsTour.EventHistory, KnightsTour.EventHistoryLite, int?>(property))
                        {
                            KnightsTour.CoreLibrary.IActionResponse deleteResponse = logic.DeleteByFK(property, fkValue);
                            Assert.IsTrue(deleteResponse.IsValid);
                        }
                    }
                }
            }
        }
        #endregion EventHistory logic tests Methods

    } // Class
} // Namespace