// © 2023 27 Software
//
// ************************************************************************
// Author           : DXterity8 Version 8.6
// Created          : March 19, 2023 7:56:06 AM
// File             : EventHistoryRepositoryTestsBase.cs
// ************************************************************************

using System;

using KnightsTour;
using KnightsTour.CoreLibrary.Enumerations;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace KnightsTourUnitTests.Entity
{
    /// <summary>
    /// Tests against the EventHistory repository.  Inherits <seealso cref="BaseDataTest" />
    /// Generated On: March 19, 2023 at 7:56:06 AM by DXterity Solutions.
    /// Generated By: DXterity8 Version 8.6.0 (see https://dxteritysolutions.com/).
    /// </summary>
    /// <remarks>
    /// This class will be regenerated when requested to stay in sync with your model.
    /// </remarks>
    [TestClass]
    public class EventHistoryRepositoryTestsBase : DataTestBase<int?>
    {
        #region EventHistory repository tests Methods

        /// <summary>
        /// Description for Event History_ Has Storage Handler.
        /// </summary>
        [TestMethod]
        public void EventHistory_HasStorageHandler()
        {
            EntityRepository_HasStorageHandler<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Get By Id.
        /// </summary>
        [TestMethod]
        public void EventHistory_GetById()
        {
            EntityRepository_GetById<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Get By Ids.
        /// </summary>
        [TestMethod]
        public void EventHistory_GetByIds()
        {
            EntityRepository_GetByIds<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Get All.
        /// </summary>
        [TestMethod]
        public void EventHistory_GetAll()
        {
            EntityRepository_GetAll<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Get All_ By Condition.
        /// </summary>
        [TestMethod]
        public void EventHistory_GetAll_ByCondition()
        {
            EntityRepository_GetAll_ByCondition<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Get By F K.
        /// </summary>
        [TestMethod]
        public void EventHistory_GetByFK()
        {
            EntityRepository_GetByFK<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Get By F Ks.
        /// </summary>
        [TestMethod]
        public void EventHistory_GetByFKs()
        {
            EntityRepository_GetByFKs<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Insert_ Single.
        /// </summary>
        [TestMethod]
        public void EventHistory_Insert_Single()
        {
            EntityRepository_Insert_Single<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Insert_ Multiple.
        /// </summary>
        [TestMethod]
        public void EventHistory_Insert_Multiple()
        {
            EntityRepository_Insert_Multiple<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Update_ Single.
        /// </summary>
        [TestMethod]
        public void EventHistory_Update_Single()
        {
            EntityRepository_Update_Single<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Update_ Multiple.
        /// </summary>
        [TestMethod]
        public void EventHistory_Update_Multiple()
        {
            EntityRepository_Update_Multiple<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Delete_ By Id.
        /// </summary>
        [TestMethod]
        public void EventHistory_Delete_ById()
        {
            EntityRepository_Delete_ById<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Delete_ By Ids.
        /// </summary>
        [TestMethod]
        public void EventHistory_Delete_ByIds()
        {
            EntityRepository_Delete_ByIds<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Delete_ By Entity.
        /// </summary>
        [TestMethod]
        public void EventHistory_Delete_ByEntity()
        {
            EntityRepository_Delete_ByEntity<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Delete_ By Entities.
        /// </summary>
        [TestMethod]
        public void EventHistory_Delete_ByEntities()
        {
            EntityRepository_Delete_ByEntities<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>();
        }

        /// <summary>
        /// Description for Event History_ Get All_ By Predicate.
        /// </summary>
        [TestMethod]
        public void EventHistory_GetAll_ByPredicate()
        {
            if (GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(EntityProperty.RecordCount) > 0)
            {
                int? maxId = GetEntityProperty<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(EntityProperty.LastId);
                EntityRepository_GetAll_ByPredicate<KnightsTour.EventHistory, KnightsTour.EventHistoryLite>(a => a.EventHistoryId < maxId);
            }
        }
        #endregion EventHistory repository tests Methods

    } // Class
} // Namespace