// © 2023 27 Software
//
// ************************************************************************
// Author           : DXterity8 Version 8.6
// Created          : March 19, 2023 7:56:06 AM
// File             : SolutionStoredProcedureTestsBase.cs
// ************************************************************************

using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;

using KnightsTour;
using KnightsTour.CoreLibrary;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace KnightsTourUnitTests.StoredProcedure
{
    /// <summary>
    /// Tests against the Solution entity stored procedures.  Inherits <seealso cref="BaseDataTest" />
    /// Generated On: March 19, 2023 at 7:56:06 AM by DXterity Solutions.
    /// Generated By: DXterity8 Version 8.6.0 (see https://dxteritysolutions.com/).
    /// </summary>
    /// <remarks>
    /// This class will be regenerated when requested to stay in sync with your model.
    /// </remarks>
    [TestClass]
    public class SolutionStoredProcedureTestsBase : DataTestBase<int?>
    {
        #region Declarations
        static SQLServerStorageHandler storageHandler = null; // A universal storage handler to support these stored procedure tests.
        #endregion Declarations

        #region Properties

        /// <summary>
        /// A universal storage handler to support these stored procedure tests.
        /// </summary>
        /// <value>
        /// The storage handler.
        /// </value>
        static SQLServerStorageHandler StorageHandler
        {
            get
            {
                if (storageHandler == null)
                {
                    storageHandler = (SQLServerStorageHandler)StorageProvider.GetHandler();
                }
                return storageHandler;
            }
        }
        #endregion Properties

        #region Solution stored procedure tests Methods

        /// <summary>
        /// Description for Solution_ Stored Procedure_ Create.
        /// </summary>
        [TestMethod]
        public void Solution_StoredProcedure_Create()
        {
            // Verify that the stored procedure exists.
            if (Enum.IsDefined(typeof(KnightsTour.Enumerations.StoredProcedure), "SolutionInsert"))
            {
                using (var transactionScope = new TransactionScope())
                {
                    // This creates a new, fully populated yet randomized entity.
                    KnightsTour.Solution solution = GetNewEntity<KnightsTour.Solution>();

                    StorageStatement statement = new StorageStatement()
                    {
                        CommandType = System.Data.CommandType.StoredProcedure,
                        // In production, the StoredProcedureTransformation should be referenced by the StoredProcedure enumeration list, for example:.
                        // Statement = EntityMapper.StoredProcedureTransformation[KnightsTour.Enumerations.StoredProcedure.SolutionInsert.ToString()];
                        Statement = EntityMapper.StoredProcedureTransformation["SolutionInsert"],
                        Parameters = new List<IParameter>
                        {
                            new KnightsTour.CoreLibrary.GenericParameter("@PuzzleId", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.PuzzleId)),
                            new KnightsTour.CoreLibrary.GenericParameter("@MemberId", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.MemberId)),
                            new KnightsTour.CoreLibrary.GenericParameter("@SolutionDuration", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.SolutionDuration)),
                            new KnightsTour.CoreLibrary.GenericParameter("@Path", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.Path)),
                            new KnightsTour.CoreLibrary.GenericParameter("@Note", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.Note)),
                        }
                    };

                    try
                    {
                        int? pkValueReturned = StorageHandler.GetValue<int?>(statement);
                        Assert.IsNotNull(pkValueReturned);
                    }
                    catch (Exception exception)
                    {
                        if (IsKeyConstraintException(exception))
                        {
                            Assert.Inconclusive("Data constraint violated or invalid trigger code detected.");
                        }

                        Assert.Fail(exception.Message);
                    }
                } // Transaction scope.
            } // Enum defined.
            else
            {
                Assert.Inconclusive("The stored procedure 'SolutionInsert' could not be verified to exist.");
            }
        }

        /// <summary>
        /// Description for Solution_ Stored Procedure_ Update.
        /// </summary>
        [TestMethod]
        public void Solution_StoredProcedure_Update()
        {
            // Verify that the stored procedure exists.
            if (Enum.IsDefined(typeof(KnightsTour.Enumerations.StoredProcedure), "SolutionUpdate"))
            {
                using (var transactionScope = new TransactionScope())
                {
                    #region Data validation
                    long totalRecords = GetEntityProperty<KnightsTour.Solution, KnightsTour.SolutionLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.RecordCount);
                    int? idToSelect = null;

                    // This creates a new, fully populated yet randomized entity.
                    KnightsTour.Solution solution = GetNewEntity<KnightsTour.Solution>();

                    // Insert a new record if required to validate this test.
                    if (totalRecords == 0)
                    {
                        try
                        {
                            IActionResponse insertResponse = new SolutionLogic("Unit test").Insert(solution);

                            if (!insertResponse.IsValid)
                            {
                                Assert.Fail(insertResponse.Messages.Where(m => m.Type == KnightsTour.CoreLibrary.Enumerations.MessageType.Negative).First().Content);
                            }
                        }
                        catch (Exception exception)
                        {
                            if (IsKeyConstraintException(exception))
                            {
                                Assert.Inconclusive("Unit test passed, unique data constraints check kicked in and verified");
                            }

                            Assert.Fail(exception.Message);
                        }
                    }
                    else
                    {
                        idToSelect = GetEntityProperty<KnightsTour.Solution, KnightsTour.SolutionLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.FirstId);
                        solution = new SolutionLogic("Unit test").GetById(idToSelect);
                    }
                    #endregion

                    #region Dynamically update the newly created solution
                    if (GetEntityProperty<KnightsTour.Solution, KnightsTour.SolutionLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.HasStringField))
                    {
                        string stringField = GetEntityProperty<KnightsTour.Solution, KnightsTour.SolutionLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.StringField);
                        string currentValue = KnightsTour.CoreLibrary.ReflectionAssistant.GetValue<KnightsTour.Solution, string>(solution, stringField);
                        string newValue = "modified";
                        if (!string.IsNullOrEmpty(currentValue))
                        {
                            newValue = currentValue + " modified.";
                            if (currentValue.StartsWith("a"))
                            {
                                newValue = currentValue.Replace("a", "z");
                            }
                        }
                        KnightsTour.CoreLibrary.ReflectionAssistant.SetValue<KnightsTour.Solution>(solution, stringField, newValue);
                    }
                    else if (GetEntityProperty<KnightsTour.Solution, KnightsTour.SolutionLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.HasIntField))
                    {
                        string intField = GetEntityProperty<KnightsTour.Solution, KnightsTour.SolutionLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.IntField);
                        int currentValue = KnightsTour.CoreLibrary.ReflectionAssistant.GetValue<KnightsTour.Solution, int>(solution, intField);
                        int newValue = currentValue + 1;
                        KnightsTour.CoreLibrary.ReflectionAssistant.SetValue<KnightsTour.Solution>(solution, intField, newValue);
                    }
                    #endregion

                    // Update the object using the stored procedure.
                    StorageStatement statement = new StorageStatement()
                    {
                        CommandType = System.Data.CommandType.StoredProcedure,
                        // In production, the StoredProcedureTransformation should be referenced by the StoredProcedure enumeration list, for example:.
                        // Statement = EntityMapper.StoredProcedureTransformation[KnightsTour.Enumerations.StoredProcedure.SolutionUpdate.ToString()];
                        Statement = EntityMapper.StoredProcedureTransformation["SolutionUpdate"],
                        Parameters = new List<IParameter>
                        {
                            new KnightsTour.CoreLibrary.GenericParameter("@SolutionId", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.SolutionId)),
                            new KnightsTour.CoreLibrary.GenericParameter("@PuzzleId", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.PuzzleId)),
                            new KnightsTour.CoreLibrary.GenericParameter("@MemberId", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.MemberId)),
                            new KnightsTour.CoreLibrary.GenericParameter("@SolutionStartDate", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.SolutionStartDate)),
                            new KnightsTour.CoreLibrary.GenericParameter("@SolutionDuration", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.SolutionDuration)),
                            new KnightsTour.CoreLibrary.GenericParameter("@Path", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.Path)),
                            new KnightsTour.CoreLibrary.GenericParameter("@Note", solution.GetDBValue(KnightsTour.Enumerations.SolutionProperty.Note)),
                        }
                    };

                    try
                    {
                        int recordsUpdated = StorageHandler.Execute(statement);

                        // Validate the record was in fact updated.
                        Assert.AreEqual(recordsUpdated, 1);
                    }
                    catch (Exception exception)
                    {
                        if (IsKeyConstraintException(exception))
                        {
                            Assert.Inconclusive("Data constraint violated or invalid trigger code detected.");
                        }

                        Assert.Fail(exception.Message);
                    }
                } // Transaction scope.
            } // Enum defined.
            else
            {
                Assert.Inconclusive("The stored procedure 'SolutionUpdate' could not be verified to exist.");
            }
        }

        /// <summary>
        /// Description for Solution_ Stored Procedure_ Get By Id.
        /// </summary>
        [TestMethod]
        public void Solution_StoredProcedure_GetById()
        {
            // Verify that the stored procedure exists.
            if (Enum.IsDefined(typeof(KnightsTour.Enumerations.StoredProcedure), "SolutionGetById"))
            {
                using (var transactionScope = new TransactionScope())
                {
                    #region Data validation
                    long totalRecords = GetEntityProperty<KnightsTour.Solution, KnightsTour.SolutionLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.RecordCount);
                    int? idToSelect = null;

                    // Insert a new record if required to validate this test.
                    if (totalRecords == 0)
                    {
                        // This creates a new, fully populated yet randomized entity.
                        KnightsTour.Solution solution = GetNewEntity<KnightsTour.Solution>();

                        try
                        {
                            IActionResponse insertResponse = new SolutionLogic("Unit test").Insert(solution);

                            if (!insertResponse.IsValid)
                            {
                                Assert.Fail(insertResponse.Messages.Where(m => m.Type == KnightsTour.CoreLibrary.Enumerations.MessageType.Negative).First().Content);
                            }
                            else
                            {
                                totalRecords = 1;
                                idToSelect = solution.SolutionId;
                            }
                        }
                        catch (Exception exception)
                        {
                            if (IsKeyConstraintException(exception))
                            {
                                Assert.Inconclusive("Data constraint violated or invalid trigger code detected.");
                            }

                            Assert.Fail(exception.Message);
                        }
                    }
                    else
                    {
                        idToSelect = GetEntityProperty<KnightsTour.Solution, KnightsTour.SolutionLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.FirstId);
                    }
                    #endregion

                    StorageStatement statement = new StorageStatement()
                    {
                        CommandType = System.Data.CommandType.StoredProcedure,
                        // In production, the StoredProcedureTransformation should be referenced by the StoredProcedure enumeration list, for example:.
                        // Statement = EntityMapper.StoredProcedureTransformation[KnightsTour.Enumerations.StoredProcedure.SolutionGetById.ToString()];
                        Statement = EntityMapper.StoredProcedureTransformation["SolutionGetById"],
                        Parameter = new KnightsTour.CoreLibrary.GenericParameter("@SolutionId", idToSelect),
                    };

                    KnightsTour.Solution record = new KnightsTour.Solution(StorageHandler.GetRecord(statement));

                    // Validate the record pk returned matches the expected identifier.
                    Assert.AreEqual(record.SolutionId, idToSelect);
                }
            }
            else
            {
                Assert.Inconclusive("The stored procedure 'SolutionGetById' could not be verified to exist.");
            }
        }

        /// <summary>
        /// Description for Solution_ Stored Procedure_ Get All.
        /// </summary>
        [TestMethod]
        public void Solution_StoredProcedure_GetAll()
        {
            // Verify that the stored procedure exists.
            if (Enum.IsDefined(typeof(KnightsTour.Enumerations.StoredProcedure), "SolutionGetAll"))
            {
                using (var transactionScope = new TransactionScope())
                {
                    #region Data validation
                    long totalRecords = GetEntityProperty<KnightsTour.Solution, KnightsTour.SolutionLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.RecordCount);

                    // Insert a new record if required to validate this test.
                    if (totalRecords == 0)
                    {
                        // This creates a new, fully populated yet randomized entity.
                        KnightsTour.Solution solution = GetNewEntity<KnightsTour.Solution>();

                        try
                        {
                            IActionResponse insertResponse = new SolutionLogic("Unit test").Insert(solution);

                            if (!insertResponse.IsValid)
                            {
                                Assert.Fail(insertResponse.Messages.Where(m => m.Type == KnightsTour.CoreLibrary.Enumerations.MessageType.Negative).First().Content);
                            }
                            else
                            {
                                totalRecords = 1;
                            }
                        }
                        catch (Exception exception)
                        {
                            if (IsKeyConstraintException(exception))
                            {
                                Assert.Inconclusive("Data constraint violated or invalid trigger code detected.");
                            }

                            Assert.Fail(exception.Message);
                        }
                    }
                    #endregion

                    StorageStatement statement = new StorageStatement()
                    {
                        CommandType = System.Data.CommandType.StoredProcedure,
                        // In production, the StoredProcedureTransformation should be referenced by the StoredProcedure enumeration list, for example:.
                        // Statement = EntityMapper.StoredProcedureTransformation[KnightsTour.Enumerations.StoredProcedure.SolutionGetAll.ToString()];
                        Statement = EntityMapper.StoredProcedureTransformation["SolutionGetAll"],
                    };

                    List<KnightsTour.Solution> records = new List<KnightsTour.Solution>();
                    foreach (dynamic dataRow in StorageHandler.GetRecords(statement))
                    {
                        records.Add(new KnightsTour.Solution(dataRow));
                    }

                    // Validate the total number of records returned match the total number of rows known to exist.
                    Assert.AreEqual(totalRecords, records.Count);
                }
            }
            else
            {
                Assert.Inconclusive("The stored procedure 'SolutionGetAll' could not be verified to exist.");
            }
        }

        /// <summary>
        /// Description for Solution_ Stored Procedure_ Delete.
        /// </summary>
        [TestMethod]
        public void Solution_StoredProcedure_Delete()
        {
            // Verify that the stored procedure exists.
            if (Enum.IsDefined(typeof(KnightsTour.Enumerations.StoredProcedure), "SolutionDelete"))
            {
                using (var transactionScope = new TransactionScope())
                {
                    #region Data validation
                    long totalRecords = GetEntityProperty<KnightsTour.Solution, KnightsTour.SolutionLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.RecordCount);
                    int? idToDelete = null;

                    // Insert a new record if required to validate this test.
                    if (totalRecords == 0)
                    {
                        // This creates a new, fully populated yet randomized entity.
                        KnightsTour.Solution solution = GetNewEntity<KnightsTour.Solution>();

                        try
                        {
                            IActionResponse insertResponse = new SolutionLogic("Unit test").Insert(solution);

                            if (!insertResponse.IsValid)
                            {
                                Assert.Fail(insertResponse.Messages.Where(m => m.Type == KnightsTour.CoreLibrary.Enumerations.MessageType.Negative).First().Content);
                            }
                            else
                            {
                                totalRecords = 1;
                                idToDelete = solution.SolutionId;
                            }
                        }
                        catch (Exception exception)
                        {
                            if (IsKeyConstraintException(exception))
                            {
                                Assert.Inconclusive("Unit test passed, unique data constraints check kicked in and verified");
                            }

                            Assert.Fail(exception.Message);
                        }
                    }
                    else
                    {
                        idToDelete = GetEntityProperty<KnightsTour.Solution, KnightsTour.SolutionLite>(KnightsTour.CoreLibrary.Enumerations.EntityProperty.FirstId);
                    }
                    #endregion

                    StorageStatement statement = new StorageStatement()
                    {
                        CommandType = System.Data.CommandType.StoredProcedure,
                        // In production, the StoredProcedureTransformation should be referenced by the StoredProcedure enumeration list, for example:.
                        // Statement = EntityMapper.StoredProcedureTransformation[KnightsTour.Enumerations.StoredProcedure.SolutionDelete.ToString()];
                        Statement = EntityMapper.StoredProcedureTransformation["SolutionDelete"],
                        Parameter = new KnightsTour.CoreLibrary.GenericParameter("@SolutionId", idToDelete),
                    };

                    try
                    {
                        int recordsDeleted = StorageHandler.Execute(statement);

                        // Validate the record was in fact deleted.
                        Assert.AreEqual(recordsDeleted, 1);
                    }
                    catch (Exception exception)
                    {
                        if (IsKeyConstraintException(exception))
                        {
                            Assert.Inconclusive("Data constraint violated or invalid trigger code detected.");
                        }
                    }
                }
            }
            else
            {
                Assert.Inconclusive("The stored procedure 'SolutionDelete' could not be verified to exist.");
            }
        }
        #endregion Solution stored procedure tests Methods

    } // Class
} // Namespace