// © 2023 27 Software
//
// ************************************************************************
// Author           : DXterity8 Version 8.6
// Created          : October 26, 2023 9:31:46 AM
// File             : DboVShareSolutionLiteBase.cs
// ************************************************************************

using System;
using System.Data;

namespace KnightsTour
{
    /// <summary>
    /// The DboVShareSolutionBase class which is the single place which defines the view properties. />
    /// Generated On: October 26, 2023 at 9:31:46 AM by DXterity Solutions.
    /// Generated By: DXterity8 Version 8.6.0 (see https://dxteritysolutions.com/).
    /// </summary>
    /// <remarks>
    /// This class will be regenerated when requested to stay in sync with your model.
    /// This class should NOT be modified - any extensions or overrides should be completed in the extended class <seealso cref="DboVShareSolution" />.
    /// </remarks>
    public abstract class DboVShareSolutionBase
    {
        #region Constructor(s)

        /// <summary>
        /// Initializes a new instance of the <see cref="DboVShareSolutionBase"/> class.
        /// Initializes a new instance of the <see cref="DboVShareSolutionBase"/> class initialized with default properties.
        /// </summary>
        public DboVShareSolutionBase() : base()
        {
            // View properties.
            SolutionId = 0;
            Code = string.Empty;
            SolutionDuration = 0M;
            SolutionStartDate = DateTime.Now;
            MemberName = string.Empty;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="DboVShareSolutionBase"/> class.
        /// Initializes a new empty instance of the DboVShareSolutionBase class from a DataRow with the DboVShareSolution view columns specified.
        /// </summary>
        /// <param name="record">A <see cref="DataRow"/>.</param>
        public DboVShareSolutionBase(DataRow record)
        {
            if (record != null)
            {
                SolutionId = record.ValueAs<int>("SolutionId");
                Code = record.ValueAs<string>("Code");
                SolutionDuration = record.ValueAs<decimal>("SolutionDuration");
                SolutionStartDate = record.ValueAs<DateTime>("SolutionStartDate");
                MemberName = record.ValueAs<string>("MemberName");
            }
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="DboVShareSolutionBase"/> class.
        /// Initializes a new empty instance of the DboVShareSolutionBase class from the record in a data reader populating only the DboVShareSolution columns specified.
        /// </summary>
        /// <param name="record">A record returned from a database reader.</param>
        public DboVShareSolutionBase(IDataRecord record)
        {
            if (record != null)
            {
                SolutionId = record.ValueAs<int>("SolutionId");
                Code = record.ValueAs<string>("Code");
                SolutionDuration = record.ValueAs<decimal>("SolutionDuration");
                SolutionStartDate = record.ValueAs<DateTime>("SolutionStartDate");
                MemberName = record.ValueAs<string>("MemberName");
            }
        }
        #endregion Constructor(s)

        #region Properties

        /// <summary>
        /// Gets or sets the solution id.
        /// </summary>
        /// <value>
        /// The solution id.
        /// </value>
        public int SolutionId
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the code.
        /// </summary>
        /// <value>
        /// The code.
        /// </value>
        public string Code
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the solution duration.
        /// </summary>
        /// <value>
        /// The solution duration.
        /// </value>
        public decimal SolutionDuration
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the solution start date.
        /// </summary>
        /// <value>
        /// The solution start date.
        /// </value>
        public DateTime SolutionStartDate
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the member name.
        /// </summary>
        /// <value>
        /// The member name.
        /// </value>
        public string MemberName
        {
            get;
            set;
        }
        #endregion Properties

    } // Class
} // Namespace