// © 2023 27 Software
//
// ************************************************************************
// Author           : DXterity8 Version 8.6
// Created          : October 14, 2023 10:21:15 AM
// File             : DifficultyLevelsControllerBase.cs
// ************************************************************************

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;

using KnightsTour.CoreLibrary;
using KnightsTour.WebAPI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Formatter;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Results;

namespace Web.ODataControllers
{
    /// <summary>
    /// The base Rest based difficulty level endpoints.
    /// Generated On: October 14, 2023 at 10:21:15 AM by DXterity Solutions.
    /// Generated By: DXterity8 Version 8.6.0 (see https://dxteritysolutions.com/).
    /// </summary>
    /// <seealso cref="Web.ODataControllers.ApiControllerBase" />
    /// <remarks>
    /// This class is overwritten every time the entity or generator version is modified to stay in sync with your model.
    /// </remarks>
    public class DifficultyLevelsControllerBase : ApiControllerBase
    {
        #region Public endpoints Methods

        /// <summary>
        /// Returns a page limited list of all DifficultyLevel entities.
        /// </summary>
        /// <returns>A <seealso cref="System.Web.Http.IActionResult" /> result.</returns>
        [EnableQuery]
        #if !DEBUG
        [Authorize]
        #endif
        public IActionResult Get()
        {
            return ExecuteCommon(_Get);
        }

        /// <summary>
        /// Returns a single DifficultyLevel entity.
        /// </summary>
        /// <param name="key">The id of the <seealso cref="KnightsTour.DifficultyLevel" /> of which to retrieve.</param>
        /// <returns>A <seealso cref="System.Web.Http.IActionResult" /> result.</returns>
        [EnableQuery]
        #if !DEBUG
        [Authorize]
        #endif
        public IActionResult Get(int key)
        {
            return ExecuteCommon(_Get, new dynamic[] { key });
        }

        /// <summary>
        /// Insert a lite <seealso cref="KnightsTour.DifficultyLevel" /> entity.
        /// </summary>
        /// <param name="difficultyLevelLite">The new <seealso cref="KnightsTour.DifficultyLevelLite" /> to insert.</param>
        /// <returns>A <seealso cref="System.Web.Http.IActionResult" /> result.</returns>
        #if !DEBUG
        [Authorize]
        #endif
        public IActionResult Post([FromBody] KnightsTour.DifficultyLevelLite difficultyLevelLite)
        {
            return ExecuteCommon(_Post, new dynamic[] { difficultyLevelLite });
        }

        /// <summary>
        /// Updated the passed<seealso cref="KnightsTour.DifficultyLevel" /> entity.
        /// </summary>
        /// <param name="difficultyLevelLite">The <seealso cref="KnightsTour.DifficultyLevelLite" /> to update.</param>
        /// <returns>A <seealso cref="System.Web.Http.IActionResult" /> result.</returns>
        #if !DEBUG
        [Authorize]
        #endif
        public IActionResult Put([FromBody] KnightsTour.DifficultyLevelLite difficultyLevelLite)
        {
            return ExecuteCommon(_Put, new dynamic[] { difficultyLevelLite });
        }

        /// <summary>
        /// Deletes a single DifficultyLevel entity.
        /// </summary>
        /// <param name="key">The id of the <seealso cref="KnightsTour.DifficultyLevel" /> of which to delete.</param>
        /// <returns>A <seealso cref="System.Web.Http.IActionResult" /> result.</returns>
        #if !DEBUG
        [Authorize]
        #endif
        public IActionResult Delete([FromODataUri] int key)
        {
            return ExecuteCommon(_Delete, new dynamic[] { key });
        }

        /// <summary>
        /// Returns all the related Puzzles entities related to the DifficultyLevel.
        /// </summary>
        /// <param name="key">The id of the <seealso cref="KnightsTour.DifficultyLevel" /> of which to retrieve the related <seealso cref="KnightsTour.Puzzle" /> entities.</param>
        /// <returns>A <seealso cref="System.Web.Http.IActionResult" /> result.</returns>
        [EnableQuery]
        [HttpGet]
        #if !DEBUG
        [Authorize]
        #endif
        public IActionResult GetPuzzles([FromODataUri] int key)
        {
            return ExecuteCommon(_GetPuzzles, new dynamic[] { key });
        }
        #endregion Public endpoints Methods

        #region CRUD Methods

        /// <summary>
        /// Returns a page limited list of all DifficultyLevel entities.
        /// </summary>
        /// <param name="arguments">A dynamic list of arguments (required by the wrapping method call 'ExecuteCommon()').</param>
        /// <returns>A <seealso cref="System.Web.Http.IActionResult" /> result.</returns>
        private IActionResult _Get(dynamic[] arguments)
        {
            KnightsTour.DifficultyLevelLogic logic = new KnightsTour.DifficultyLevelLogic(UserName);
            if (arguments == null)
            {
                IEnumerable<KnightsTour.DifficultyLevel> difficultyLevels = logic.GetAll().AsQueryable();
                return Ok(difficultyLevels);
            }
            else
            {
                KnightsTour.DifficultyLevel difficultyLevel = logic.GetById(arguments[0]);
                if (difficultyLevel == null)
                {
                    return new NotFoundResult();
                }
                else
                {
                    SingleResult<KnightsTour.DifficultyLevel> creationResult = SingleResult.Create(new[] { difficultyLevel }.AsQueryable());
                    return Ok(creationResult);
                }
            }
        }

        /// <summary>
        /// Insert a lite <seealso cref="KnightsTour.DifficultyLevel" /> entity.
        /// </summary>
        /// <param name="arguments">A dynamic list of arguments (required by the wrapping method call 'ExecuteCommon()').</param>
        /// <returns>A <seealso cref="System.Web.Http.IActionResult" /> result.</returns>
        private IActionResult _Post(dynamic[] arguments)
        {
            KnightsTour.DifficultyLevelLogic logic = new KnightsTour.DifficultyLevelLogic(UserName);

            KnightsTour.DifficultyLevel newDifficultyLevel = new KnightsTour.DifficultyLevel(arguments[0]);
            IActionResponse response = logic.Insert(newDifficultyLevel);

            if (response.IsValid)
            {
                return Created(newDifficultyLevel);
            }
            else
            {
                return StatusCode((int)HttpStatusCode.BadRequest, response);
            }
        }

        /// <summary>
        /// Updated the passed<seealso cref="KnightsTour.DifficultyLevel" /> entity.
        /// </summary>
        /// <param name="arguments">A dynamic list of arguments (required by the wrapping method call 'ExecuteCommon()').</param>
        /// <returns>A <seealso cref="System.Web.Http.IActionResult" /> result.</returns>
        private IActionResult _Put(dynamic[] arguments)
        {
            KnightsTour.DifficultyLevelLite difficultyLevelLite = arguments[0];
            if (difficultyLevelLite.Id.HasValue)
            {
                KnightsTour.DifficultyLevelLogic logic = new KnightsTour.DifficultyLevelLogic(UserName);

                KnightsTour.DifficultyLevel existingDifficultyLevel = logic.GetById(difficultyLevelLite.DifficultyLevelId.Value);
                if (existingDifficultyLevel != null)
                {
                    existingDifficultyLevel.UpdateFromLite(difficultyLevelLite);
                    if (existingDifficultyLevel.IsModified())
                    {
                        IActionResponse response = logic.Update(existingDifficultyLevel);

                        if (response.IsValid)
                        {
                            return Updated(existingDifficultyLevel);
                        }
                        else
                        {
                            return StatusCode((int)HttpStatusCode.BadRequest, response);
                        }
                    }
                    else
                    {
                        return StatusCode((int)HttpStatusCode.NoContent, "No update required.");
                    }
                }
                else
                {
                    return new NotFoundResult();
                }
            }
            else
            {
                return StatusCode((int)HttpStatusCode.BadRequest, "When updating a difficultyLevel via a HttpPut verb, DifficultyLevelId must be set.");
            }
        }

        /// <summary>
        /// Deletes a single DifficultyLevel entity.
        /// </summary>
        /// <param name="arguments">A dynamic list of arguments (required by the wrapping method call 'ExecuteCommon()').</param>
        /// <returns>A <seealso cref="System.Web.Http.IActionResult" /> result.</returns>
        private IActionResult _Delete(dynamic[] arguments)
        {
            KnightsTour.DifficultyLevelLogic logic = new KnightsTour.DifficultyLevelLogic(UserName);
            IActionResponse response = logic.Delete(arguments[0]);

            if (response.IsValid)
            {
                return StatusCode((int)HttpStatusCode.NoContent, response);
            }
            else
            {
                return StatusCode((int)HttpStatusCode.BadRequest, response);
            }
        }
        #endregion CRUD Methods

        #region Child CRUD access Methods

        /// <summary>
        /// Returns all the related Puzzles entities related to the DifficultyLevel.
        /// </summary>
        /// <param name="arguments">A dynamic list of arguments (required by the wrapping method call 'ExecuteCommon()').</param>
        /// <returns>A <seealso cref="System.Web.Http.IActionResult" /> result.</returns>
        private IActionResult _GetPuzzles(dynamic[] arguments)
        {
            KnightsTour.DifficultyLevelLogic logic = new KnightsTour.DifficultyLevelLogic(UserName);
            KnightsTour.DifficultyLevel difficultyLevel = logic.GetById(arguments[0]);
            if (difficultyLevel == null)
            {
                return new NotFoundResult();
            }
            else
            {
                return Ok(difficultyLevel.Puzzles.AsQueryable());
            }
        }
        #endregion Child CRUD access Methods

    } // Class
} // Namespace