// © 2023 27 Software
//
// ************************************************************************
// Author           : DXterity8 Version 8.6
// Created          : January 13, 2023 7:25:01 AM
// File             : SolutionLite.cs
// ************************************************************************

using System;

namespace KnightsTour
{
    /// <summary>
    /// Represents a lite version of the <see cref="Solution"/> object.
    /// Generated On: January 13, 2023 at 7:25:01 AM by DXterity Solutions.
    /// Generated By: DXterity8 Version 8.6.0 (see https://dxteritysolutions.com/).
    /// </summary>
    /// <remarks>
    /// Helpful for API's.
    /// You can Extended the lite object as you require.
    /// </remarks>
    public class SolutionLite : SolutionLiteBase, KnightsTour.CoreLibrary.IEntityLite<int?>
    {
        #region Extended Constructor(s)

        /// <summary>
        /// Initializes a new instance of the <see cref="SolutionLite"/> class.
        /// Initializes a new instance of the <see cref="SolutionLite"/> class.
        /// </summary>
        /// <example>
        /// <code>
        /// SolutionLite solutionLite = new SolutionLite();
        /// </code>
        /// </example>
        public SolutionLite() : base()
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SolutionLite"/> class.
        /// Initializes a new instance of the <see cref="SolutionLite"/> class from its full class representation.
        /// </summary>
        /// <param name="solution">The <see cref="Solution"/>.</param>
        /// <example>
        /// <code>
        /// SolutionLite solutionLite = new SolutionLite(new SolutionLogic.GetByPK(1));
        /// if (solutionLite != null)
        /// {
        ///     Console.WriteLine(solutionLite.ToString());
        /// }
        /// </code>
        /// </example>
        public SolutionLite(Solution solution) : base(solution)
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SolutionLite"/> class.
        /// Initializes a new instance of the <see cref="SolutionLite"/> class from its base class representation.
        /// </summary>
        /// <param name="solutionBase">The <see cref="SolutionBase"/>.</param>
        public SolutionLite(SolutionBase solutionBase) : base(solutionBase)
        {
        }
        #endregion Extended Constructor(s)

        #region Extended Declarations
        #endregion Extended Declarations

        #region Extended Properties
        #endregion Extended Properties

        #region Extended Methods
        #endregion Extended Methods

    } // Class
} // Namespace